# 'production' only prints info and above. 'development' also prints debug
environment: production
eth_rpc_url: http://localhost:8545
eth_ws_url: ws://localhost:8545

# address which the aggregator listens on for operator signed messages
aggregator_server_ip_port_address: localhost:8090
bls_public_key_compendium_address: 0x322813Fd9A801c5507c9de605d63CEA4f2CE6c44
avs_service_manager_address: 0xc5a5C42992dECbae36851359345FE25997F5C42d
enable_metrics: true
