version: '3'



services:
  devnet:
    build:
      context: ./contracts/scripts/anvil/state
      dockerfile: Dockerfile
    networks:
      - aligned-network
    ports:
      - "8545:8545"

  aggregator:
    build:
      context: ./
      dockerfile: aggregator/Dockerfile
    depends_on:
      - devnet
    networks:
      - aligned-network
    ports:
      - "8090:8090"

  operator:
    build:
      context: ./
      dockerfile: operator/Dockerfile
    networks:
      - aligned-network
    depends_on:
      - devnet
networks:
  aligned-network: