version: '3'

services:
  devnet:
    build:
      context: ./contracts/scripts/anvil/state
      dockerfile: Dockerfile
    ports:
      - "8545:8545"  # Expose port 8545
    networks:
      devnet_network:
        aliases:
          - devnet

  aggregator:
    build:
      context: ./
      dockerfile: aggregator/Dockerfile
    networks:
      devnet_network:
        aliases:
          - aggregator

  operator:
    build:
      context: ./
      dockerfile: operator/Dockerfile
    networks:
      devnet_network:
        aliases:
          - operator


networks:
  devnet_network:
    driver: bridge
