version: '3'

services:
  devnet:
    build:
      context: ./contracts/scripts/anvil/state
      dockerfile: Dockerfile
    network_mode: host

  aggregator:
    build:
      context: ./
      dockerfile: aggregator/Dockerfile
    depends_on:
      - devnet
    network_mode: host

  operator-1:
    build:
      context: ./
      dockerfile: operator/Dockerfile
    depends_on:
      - devnet
    network_mode: host

  operator-2:
    build:
      context: ./
      dockerfile: operator/Dockerfile
    depends_on:
      - devnet
    network_mode: host

  operator-3:
    build:
      context: ./
      dockerfile: operator/Dockerfile
    depends_on:
      - devnet
    network_mode: host