# 'production' only prints info and above. 'development' also prints debug
environment: "development"
aligned_layer_deployment_config_file_path: "../../contracts/script/output/devnet/alignedlayer_deployment_output.json"
eigen_layer_deployment_config_file_path: "../../contracts/script/output/devnet/eigenlayer_deployment_output.json"
eth_rpc_url: "http://localhost:8545"
eth_ws_url: "ws://localhost:8545"
eigen_metrics_ip_port_address: "localhost:9090"
ecdsa:
  private_key_store_path: "../../config-files/anvil.ecdsa.key.json"
  private_key_store_password: ""
bls:
  private_key_store_path: "../../config-files/anvil.bls.key.json"
  private_key_store_password: ""
