name: build-go-projects

on:
  merge_group:
  push:
    branches: [main]
  pull_request:
    branches: ["*"]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.22'
          cache: false
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: nightly-2024-01-25
          components: llvm-tools, rustc-dev
      - name: Build aggregator
        run: go build aggregator/cmd/main.go
      - name: Build SP1
        run: make build-sp1-linux
      - name: Build operator
        run: go build operator/cmd/main.go
      - name: Build task sender
        run: go build task_sender/cmd/main.go
