on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

name: build
jobs:
  build-and-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.22
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build aggregator
        run: go build aggregator/cmd/main.go
      - name: Build operator
        run: go build operator/cmd/main.go
      - name: Build task sender
        run: go build operator/cmd/main.go
      - name: Run linters
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.46.2
    