name: Integration test
on:
  push:
    branches:
      - main
  pull_request:
    branches: ["*"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # this read ok the vars
      # - name: Test runningh bash
      #   run: |
      #     . ./scripts/mint_mock_token.sh "config-files/config.yaml" 1000

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1

      - name: install go
        uses: actions/setup-go@v5

      - name: Install YQ
        uses: dcarbone/install-yq-action@latest
      
      - name: Install deps
        run: |
            go install github.com/maoueh/zap-pretty@latest
            go install github.com/ethereum/go-ethereum/cmd/abigen@latest
            go install github.com/Layr-Labs/eigenlayer-cli/cmd/eigenlayer@latest
      
      - name: Setup GO PATH
        run: echo "export PATH=$PATH:$GITHUB_WORKSPACE/go/bin" >> $GITHUB_ENV
      
      - name: Run integration test
        run: |
            make integration-test
      
      # - name: Run Anvil
      #   run: |
      #       make anvil-start &
      
      # - name: Run Aggregator
      #   run: |
      #       make aggregator-start &

      # - name: Register Operator
      #   run: |
      #       sleep 10
      #       export CONFIG_FILE="config-files/config.yaml"
      #       make operator-full-registration
      
      # - name: Run Operator
      #   run: |
      #       sleep 5
      #       export CONFIG_FILE="config-files/config.yaml"
      #       make operator-start &

      # - name: Send tasks
      #   run: |
      #     sleep 60
      #     echo sending task 1
      #     make send-plonk_bls12_381-proof

      #     echo sending task 2
      #     make send-plonk_bn254-proof
      #     sleep 60
      
      # - name: Check results
      #   run: |
      #     go test tests/integration_test.go -v
