name: Integration test
on:
  push:
    branches:
      - main
  pull_request:
    branches: ["*"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1

      - name: Install YQ
        uses: chrisdickinson/setup-yq@latest

      - name: Install deps
        run: |
            make deps

      - name: Run Anvil
        run: |
            make integration-test
