name: Integration test
on:
  push:
    branches:
      - main
  pull_request:
    branches: ["*"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1

      - name: Install YQ
        uses: chrisdickinson/setup-yq@latest

      - name: Run Anvil
        run: |
            go install github.com/maoueh/zap-pretty@latest
            go install github.com/ethereum/go-ethereum/cmd/abigen@latest
            make integration-test
