name: Integration test
on:
  push:
    branches:
      - main
  pull_request:
    branches: ["*"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1

      - name: install go
        uses: actions/setup-go@v5

      - name: Install YQ
        uses: dcarbone/install-yq-action@v1.1.1
        with:
          version: 'v4.43.1'
      
      - name: Install deps
        run: |
            go install github.com/maoueh/zap-pretty@latest
            go install github.com/ethereum/go-ethereum/cmd/abigen@latest
            go install github.com/Layr-Labs/eigenlayer-cli/cmd/eigenlayer@latest
      
      - name: Setup GO PATH
        run: echo "export PATH=$PATH:$GITHUB_WORKSPACE/go/bin" >> $GITHUB_ENV
      
      - name: Run integration test
        run: |
            make integration-test
