name: Integration test
on:
  push:
    branches:
      - main
  pull_request:
    branches: ["*"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1

      - name: install go
        uses: actions/setup-go@v5

      - name: Install YQ
        uses: chrisdickinson/setup-yq@latest
      
      - name: Install deps
        run: |
            go install github.com/maoueh/zap-pretty@latest
            go install github.com/ethereum/go-ethereum/cmd/abigen@latest
            go install github.com/Layr-Labs/eigenlayer-cli/cmd/eigenlayer@latest
      
      - name: Setup GO PATH
        run: echo "export PATH=$PATH:$GITHUB_WORKSPACE/go/bin" >> $GITHUB_ENV
      
      - name: Run Anvil
        run: |
            make anvil-start &
      
      - name: Run Aggregator
        run: |
            make aggregator-start &
      
      - name: Run Opperator
        run: |
            export CONFIG_FILE=config-files/config.yaml
            sleep 10
            . make operator-get-eth && \
            . make operator-register-with-eigen-layer && \
            ./scripts/mint_mock_token.sh $(CONFIG_FILE) 1000 && \
            . make operator-deposit-into-mock-strategy && \
            . make operator-register-with-aligned-layer

            make operator-full-registration
            sleep 5
            make operator-start &

      - name: Send tasks
        run: |
          sleep 60
          echo sending task 1
          make send-plonk_bls12_381-proof

          echo sending task 2
          make send-plonk_bn254-proof
          sleep 60
      
      - name: Check results
        run: |
          go test tests/integration_test.go -v
