name: Integration test
on:
  push:
    branches:
      - main
  pull_request:
    branches: ["*"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1

      - name: Run Anvil
        run: |
            make integration-test &

      - name: Run Anvil
        run: |
            go test tests/integration_test.go -v
            exit 0
