name: test-halo2-ipa

on:
  merge_group:
  push:
    branches: [main]
  pull_request:
    branches: ["*"]

jobs:
    test:
      runs-on: ubuntu-latest
      steps:
        - name: Clear device space
          run: |
            sudo rm -rf "$AGENT_TOOLSDIRECTORY"
            sudo rm -rf /usr/local/lib/android
            sudo rm -rf /opt/ghc
            sudo rm -rf /usr/local/.ghcup
            sudo rm -rf /usr/share/dotnet
            sudo rm -rf /opt/ghc
            sudo rm -rf "/usr/local/share/boost"
        - uses: actions/checkout@v4
        - uses: actions/setup-go@v5
          with:
            go-version: '1.22'
            cache: false

        - name: Test Halo2-IPA go bindings
          run: make test_halo2_ipa_go_bindings_linux
