name: test-sp1

on:
  merge_group:
  push:
    branches: [main]
  pull_request:
    branches: ["*"]

jobs:
    test:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4
        - uses: actions/setup-go@v5
          with:
            go-version: '1.22'
            cache: false
        - name: Build SP1
          run: make build-sp1-linux
        - name: Build operator
          run: go build operator/cmd/main.go
        - name: Test sp1 rust
          run: make test-sp1-rust-ffi
        - name: Test sp1 go
          run: make test-sp1-go-bindings