name: test-sp1

on:
  merge_group:
  push:
    branches: [main]
  pull_request:
    branches: ["*"]

jobs:
    test:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4
        - uses: actions/setup-go@v5
          with:
            go-version: '1.22'
            cache: false
        - name: Test SP1 Rust
          run: make test_sp1_rust_ffi
        - name: Test SP1 go bindings
          run: make test_sp1_go_bindings_linux
